//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> SupplyId { get; set; }
        public bool IsRead { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; } = DateTime.Now;
    
        public virtual Supply Supply { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
