//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderHistory = new HashSet<OrderHistory>();
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int ClientId { get; set; }
        public decimal TotalCost { get; set; }
        public int DeliveryType { get; set; }
        public int WorkerId { get; set; }
        public int Status { get; set; }
        public Nullable<int> DeliveryId { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
