//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiaShopEntities : DbContext
    {
        public DiaShopEntities()
            : base("name=DiaShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Delivery> Delivery { get; set; }
        public DbSet<Favorite> Favorite { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderHistory> OrderHistory { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<ProductOrder> ProductOrder { get; set; }
        public DbSet<Schedule> Schedule { get; set; }
        public DbSet<Store> Store { get; set; }
        public DbSet<Supply> Supply { get; set; }
        public DbSet<SupplyProduct> SupplyProduct { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<User> User { get; set; }
    }
}
