//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public System.DateTime DateStart { get; set; }
        public int UserId { get; set; }
        public int Hours { get; set; }
        public System.DateTime FactStartAt { get; set; }
        public System.DateTime FactExitAt { get; set; }
        public int FactHours { get; set; }
    
        public virtual User User { get; set; }
    }
}
