//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public Supply()
        {
            this.SupplyProduct = new HashSet<SupplyProduct>();
        }
    
        public int Id { get; set; }
        public int SupplierId { get; set; }
        public int UserId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime ArrivedDate { get; set; }
        public decimal TotalCost { get; set; }
        public System.DateTime AroundDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<SupplyProduct> SupplyProduct { get; set; }
    }
}
