//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Notification = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime StartAt { get; set; }
        public System.DateTime EndAt { get; set; }
        public int AuthorId { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notification { get; set; }
        public virtual User User { get; set; }
    }
}
