//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Delivery = new HashSet<Delivery>();
            this.Favorite = new HashSet<Favorite>();
            this.OrderHistory = new HashSet<OrderHistory>();
            this.OrderHistory1 = new HashSet<OrderHistory>();
            this.Schedule = new HashSet<Schedule>();
            this.Supply = new HashSet<Supply>();
            this.Supply1 = new HashSet<Supply>();
            this.Task = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public int Role { get; set; }
        public string AvatarKey { get; set; }
        public int StoreId { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Delivery> Delivery { get; set; }
        public virtual ICollection<Favorite> Favorite { get; set; }
        public virtual ICollection<OrderHistory> OrderHistory { get; set; }
        public virtual ICollection<OrderHistory> OrderHistory1 { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<Supply> Supply { get; set; }
        public virtual ICollection<Supply> Supply1 { get; set; }
        public virtual ICollection<Task> Task { get; set; }
    }
}
