//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopDiaShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Favorites = new HashSet<Favorites>();
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
        public decimal Cost { get; set; }
        public string Image { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
